# Generated by Django 4.2.2 on 2024-04-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(choices=[('GENA', 'General Arts'), ('GENS', 'General Science'), ('BUSI', 'Business'), ('VART', 'Visual Arts'), ('HOME', 'Home Economics'), ('AGRI', 'Agricultural Science'), ('TECH', 'Technical Skills')], max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField(choices=[('FIRST YEAR', 'FIRST YEAR'), ('SECOND YEAR', 'SECOND YEAR'), ('THIRD YEAR', 'THIRD YEAR')])),
            ],
        ),
    ]
