# Generated by Django 4.2.2 on 2024-04-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('GENA', 'General Arts'), ('GENS', 'General Science'), ('BUSI', 'Business'), ('VART', 'Visual Arts'), ('HOME', 'Home Economics'), ('AGRI', 'Agricultural Science'), ('TECH', 'Technical Skills')], max_length=255, unique=True),
        ),
    ]
