# Generated by Django 4.2.2 on 2024-04-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_code_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[('1', 'FIRST YEAR'), ('2', 'SECOND YEAR'), ('3', 'THIRD YEAR')]),
        ),
    ]
