# Generated by Django 4.2.2 on 2024-04-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[('FIRST YEAR', 'First Year'), ('SECOND YEAR', 'Second Year'), ('THIRD YEAR', 'Third Year')]),
        ),
    ]
