# Generated by Django 4.2.2 on 2024-04-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('FIRST YEAR', 'First Year'), ('SECOND YEAR', 'Second Year'), ('THIRD YEAR', 'Third Year')], max_length=255),
        ),
    ]
