# Generated by Django 4.2.2 on 2024-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_description_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('GENARAL ARTS', 'General Arts'), ('GENERAL SCIENCE', 'General Science'), ('BUSINESS', 'Business'), ('VISUAL ART', 'Visual Arts'), ('HOME SCIENCE', 'Home Economics'), ('AGRIC SCIENCE', 'Agricultural Science'), ('TECHNICAL SKILLS', 'Technical Skills')], max_length=255, unique=True),
        ),
    ]
