# Generated by Django 4.2.2 on 2024-04-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('name', models.CharField(choices=[('Achimota', 'Achimota School'), ('Mfantsipim', 'Mfantsipim School'), ('Adisadel', 'Adisadel College'), ("St. Augustine's", "St. Augustine's College"), ('Prempeh', 'Prempeh College'), ('Opoku Ware', 'Opoku Ware School'), ("Wesley Girls'", "Wesley Girls' High School"), ('PRESEC', "Presbyterian Boys' Secondary School (PRESEC)"), ("St. Peter's", "St. Peter's Senior High School"), ('Ghana National', 'Ghana National College'), ('KETASCO', 'Keta Senior High Technical School (KETASCO)'), ('Adventist', 'Adventist Senior High School'), ('St. Louis', 'St. Louis Senior High School'), ('Tamasco', 'Tamale Senior High School (Tamasco)'), ('Ghanata', 'Ghanata Senior High School'), ("St. Mary's", "St. Mary's Senior High School"), ('Labone', 'Labone Senior High School'), ('Achimota SHS', 'Achimota Senior High School'), ('Pope John', 'Pope John Senior High School'), ("Adventist Girls'", "Adventist Girls' Senior High School"), ('GIS', 'Ghana International School'), ('Lutheran SHS', 'Lutheran Senior High School'), ('Alsyd Academy', 'Alsyd Academy'), ('Galaxy International', 'Galaxy International School'), ('Maranatha University College SHS', 'Maranatha University College Senior High School'), ('SOS-Hermann Gmeiner International', 'SOS-Hermann Gmeiner International College'), ('Lincoln Community', 'Lincoln Community School'), ('Regent University College SHS', 'Regent University College Senior High School'), ('Morning Star', 'Morning Star School'), ('WASS', 'West African Secondary School (WASS)')], max_length=100, unique=True)),
                ('location', models.CharField(choices=[('KUMASI', 'Kumasi'), ('TAMALE', 'Tamale'), ('ACCRA', 'Accra'), ('TECHIMAN', 'Techiman'), ('SUNYANI', 'Sunyani'), ('YENDI', 'Yendi'), ('SALAGA', 'Salaga'), ('HO', 'Ho'), ('KINTAMPO', 'Kintampo'), ('WALEWALE', 'Walewale'), ('KOFORIDUA', 'Koforidua'), ('WA', 'Wa')], max_length=100)),
                ('contact_phone', models.CharField(default='+1234567890', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('established_year', models.DateField(max_length=255)),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_contact', models.CharField(default='+00-000-000-00', max_length=20)),
                ('administrator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('administrator_contact', models.CharField(default='+00-000-000-00', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
