# Generated by Django 4.2.2 on 2024-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='established_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, choices=[('Achimota School', 'ACCRA'), ('Mfantsipim School', 'CAPE COAST'), ('Adisadel College', 'CAPE COAST'), ("St. Augustine's College", 'CAPE COAST'), ('Prempeh College', 'KUMASI'), ('Opoku Ware School', 'KUMASI'), ("Wesley Girls' High School", 'CAPE COAST'), ("Presbyterian Boys' Secondary School (PRESEC)", 'ACCRA'), ("St. Peter's Senior High School", 'CAPE COAST'), ('Ghana National College', 'CAPE COAST'), ('Keta Senior High Technical School (KETASCO)', 'KETA'), ('Adventist Senior High School', 'TECHIMAN'), ('St. Louis Senior High School', 'KUMASI'), ('Tamale Senior High School (Tamasco)', 'TAMALE'), ('Ghanata Senior High School', 'ACCRA'), ("St. Mary's Senior High School", 'ACCRA'), ('Labone Senior High School', 'ACCRA'), ('Achimota Senior High School', 'ACCRA'), ('Pope John Senior High School', 'KOFORIDUA'), ("Adventist Girls' Senior High School", 'ACCRA'), ('Ghana International School', 'ACCRA'), ('Lutheran Senior High School', 'ACCRA'), ('Alsyd Academy', 'ACCRA'), ('Galaxy International School', 'ACCRA'), ('Maranatha University College Senior High School', 'ACCRA'), ('SOS-Hermann Gmeiner International College', 'ACCRA'), ('Lincoln Community School', 'ACCRA'), ('Regent University College Senior High School', 'ACCRA'), ('Morning Star School', 'ACCRA'), ('West African Secondary School (WASS)', 'ACCRA')], max_length=100, null=True),
        ),
    ]
