# Generated by Django 4.2.2 on 2024-04-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_name'),
        ('schools', '0002_location_alter_school_established_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='schools', to='courses.course'),
        ),
    ]
