# Generated by Django 4.2.2 on 2024-04-25 14:37

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_class_course'),
        ('schools', '0002_location_alter_school_established_year_and_more'),
        ('courses', '0006_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('surname', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('aggregate_of_best_six', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raw_score', models.PositiveIntegerField(blank=True, null=True, validators=[students.models.Student.validate_non_negative])),
                ('enrolment_code', models.CharField(max_length=20)),
                ('enrolment_form_image', models.ImageField(blank=True, null=True, upload_to='enrolment_forms/')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('religion', models.CharField(choices=[('CHRISTIAN', 'Christian'), ('MUSLIM', 'Muslim'), ('TRADITIONALIST', 'Traditionalist')], max_length=255)),
                ('religious_denomination', models.CharField(blank=True, choices=[('BAPTIST', 'Baptist'), ('PENTECOST', 'Pentecost'), ('METHODIST', 'Methodist'), ('PRESBY', 'Presby'), ('ASSEMBLES OF GOD', 'Assembles of God'), ('CATHOLIC', 'Catholic'), ('ANGLICAN', 'Anglican')], max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('town', models.CharField(choices=[('WALEWALE', 'Walewale'), ('TAMALE', 'Tamale'), ('ACCRA', 'Accra'), ('TECHIMAN', 'Techiman'), ('KUMASI', 'Kumasi'), ('HO', 'Ho'), ('JEMA', 'Jema')], max_length=255)),
                ('region', models.CharField(choices=[('ASHANTI', 'Ashanti'), ('BONO', 'Bono'), ('BONO EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('GREATER ACCRA', 'Greater Accra'), ('NORTHERN', 'Northern'), ('SAVANNAH', 'Savannah'), ('NORTH EAST', 'North East'), ('UPPER EAST', 'Upper East'), ('VOLTA', 'Volta'), ('OTI', 'Oti'), ('WESTERN', 'Western'), ('WESTERN NORT', 'Western Nort')], max_length=255)),
                ('district', models.CharField(choices=[('WALEWALE WEST', 'Welewale West'), ('TAMALE WEST', 'Tamale West'), ('TECHIMAN WEST', 'Techiman West')], max_length=255)),
                ('interests', models.TextField(blank=True, choices=[('DEBATING CLUB', 'Debating Club'), ('ARTHLETICS', 'Arthletics'), ('FOOTBALL', 'Football'), ('OTHERS', 'others')], max_length=255)),
                ('ghana_card_or_nhis_number', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(choices=[('CROP FARMING', 'Crop Farming'), ('TRADING', 'Trading'), ('CHARCOAL PRODUCTION', 'Charcoal Production'), ('ANIMALS FARMING', 'Animals Farming'), ('HUNTING', 'Hunting'), ('TEACHING', 'Teaching'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(choices=[('CROP FARMING', 'Crop Farming'), ('TRADING', 'Trading'), ('CHARCOAL PRODUCTION', 'Charcoal Production'), ('ANIMALS FARMING', 'Animals Farming'), ('HUNTING', 'Hunting'), ('TEACHING', 'Teaching'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('residential_telephone', models.CharField(max_length=20)),
                ('guardian_digital_address', models.CharField(blank=True, max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('other_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('admitted_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('class_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
        ),
    ]
