# Generated by Django 4.2.2 on 2024-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='current_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
